---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: default
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox-container
        image: busybox:latest
        # keep the container running
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; echo $POD_NAME; echo sleeping-30-secs; do sleep 30; done;" ]
        resources:
          requests:
            # 0.030 of a CPU
            cpu: 30m
            # Limits and requests for memory are measured in bytes. 
            # You can express memory as a plain integer or as a fixed-point number 
            # using one of these quantity suffixes: E, P, T, G, M, k. 
            # You can also use the power-of-two equivalents: Ei, Pi, Ti, Gi, Mi, Ki. 
            # For example, the following represent roughly the same value:
            # 128974848, 129e6, 129M,  128974848000m, 123Mi
            # 64 Mebibytes
            memory: 64Mi
          limits:
            # 0.100 of a CPU
            cpu: 100m
            # Pay attention to the case of the suffixes. If you request 400m of memory, 
            # this is a request for 0.4 bytes. Someone who types that probably meant 
            # to ask for 400 mebibytes (400Mi) or 400 megabytes (400M).
            memory: 128Mi
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
                
